services:
  docs:
    image: weather_api_wrapper_service_local_docs
    container_name: weather_api_wrapper_service_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./weather_api_wrapper_service:/app/weather_api_wrapper_service:z
    ports:
      - '9000:9000'
    command: /start-docs
